version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 715841326909.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t myapp-repo .
      - docker tag myapp-repo:latest 715841326909.dkr.ecr.ap-south-1.amazonaws.com/myapp-repo
  post_build:
    commands:
      - echo Pushing image...
      - docker push 715841326909.dkr.ecr.ap-south-1.amazonaws.com/myapp-repo
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"myapp","imageUri":"715841326909.dkr.ecr.ap-south-1.amazonaws.com/myapp-repo:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
